FROM node:20

WORKDIR /app
COPY . .

RUN npm install -g pnpm @angular/cli
RUN pnpm install

WORKDIR /app/apps/admin-web

EXPOSE 4000

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4000"]
