version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: widu-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: widu-redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - redis-server
      - '--save'
      - ''
      - '--appendonly'
      - 'no'

  api-core:
    build:
      context: .
      dockerfile: apps/api-core/Dockerfile
    container_name: widu-api-core
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - CONFIG_PATH=apps/api-core/config
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./config/.env.dev:/app/apps/api-core/config/.env

  frontend-web:
    image: node:20
    container_name: widu-web
    restart: always
    ports:
      - "4200:4200"
    working_dir: /app
    volumes:
      - .:/app
    command: >-
      sh -c "npm install -g pnpm @angular/cli &&
      cd apps/frontend-web &&
      pnpm install &&
      pnpm run start"

  admin-web:
    image: node:20
    container_name: widu-admin-web
    restart: always
    ports:
      - "4000:4000"
    working_dir: /app
    depends_on:
      - api-core
    volumes:
      - .:/app
    command: >-
      sh -c "npm install -g pnpm @angular/cli &&
      cd apps/admin-web &&
      pnpm install &&
      pnpm run start"

volumes:
  mongo_data:
